In [5]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
import numpy as np
print(np.array([8,4,6,0,2]))

[8 4 6 0 2]


In [8]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |

In [13]:
print('Create a 2-D array by passing a list of lists into arrays().')
A=np.array([[1,2,3],[4,5,6] ])
print(A)
print('Access elements of the array with brackets.')
print(A[0,1],A[0,2])
print('The elements of a 2-D array are 1-D arrays.')
print(A[0])

Create a 2-D array by passing a list of lists into arrays().
[[1 2 3]
 [4 5 6]]
Access elements of the array with brackets.
2 3
The elements of a 2-D array are 1-D arrays.
[1 2 3]


In [35]:
def dotArray(X,Y):

    Z=np.dot(X,Y)
    print(Z)

X=np.array([[1,2,3],[4,5,6] ])
Y=np.array([ [2,4,-5,6],[-1,7,9,3],[3,2,-7,-2] ])
dotArray(X,Y)


[[  9  24  -8   6]
 [ 21  63 -17  27]]


In [24]:
A=np.array([3,-4,1])
B=np.array([5,2,3])
print(A+10)
print(B*4)
print(A+B)
print(A*B)


[13  6 11]
[20  8 12]
[ 8 -2  4]
[15 -8  3]


In [27]:
A=np.array([[1,2,3],[4,5,6]])
A.dtype

dtype('int32')

In [36]:
x=np.arange(0,50,10)
index =np.array([3,1,4])
print(x[index])
mask =np.array([True,False,False,True,False])
print(x[mask])

[30 10 40]
[ 0 30]


In [39]:
y=np.arange(10,20,2)
print(y)
mask=y>15
print (mask)
print(y[mask])

y[mask]=100
print(y)

[10 12 14 16 18]
[False False False  True  True]
[16 18]
[ 10  12  14 100 100]


In [40]:
from sklearn import datasets
iris=datasets.load_iris()
print(iris.filename)

C:\Users\NODE\anaconda3\lib\site-packages\sklearn\datasets\data\iris.csv


In [48]:
iris_data=np.genfromtxt('C:\\Users\\NODE\\anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv',
                       delimiter=",",skip_header=1)
print("mean of {} is {}".format(iris.feature_names[0],iris_data[:,0].mean()))

mean of sepal length (cm) is 5.843333333333334


In [49]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']